#!/usr/bin/env bash
# Installing firewall but allowing some traffics to pass

sudo apt update -y
sudo apt install ufw -y

sudo ufw enable
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
