#!/usr/bin/env bash
#Updates the current state of the server

sudo apt-get -y update
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
echo "Holberton School for the win!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm custom_404.html index.nginx-debian.html;
	server_name _;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	location /xyz {
		return 404;
	}
	# Custom error 404 page
	error_page 404 /custom_404.html;

	location = /custom_404.html {
	internal;
}
}" > /etc/nginx/sites-available/default
sudo chown -R root:root /var/www/html
sudo chown -R root:root /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
